type ProductFilterProps = {
  start_date?: string | null
  end_date?: string | null
  ativado?: string | null
}
type ProductResponseApi = {
  id: number;
  nome: string;
  descricao: string;
  preco: number | string;
  fotos: string[];
  ativado: boolean;
  video?: string;
  qtd_vendas?: string;
  categoriaid: string;
  subcategoriaid?: string;
  marcaid: string;
  ncm: string;
  preco_custo: string;
  preco_compra: string;
  profundidade: string;
  data_validade: string;
  unidade_caixa: string;
  tipo_item: string;
  tributos: string;
  codigo_pai: string;
  codigo_integracao: string;
  cest: string;
  volume: string;
  peso_bruto: string;
  gtin_ean: string;
  gtin_ean_embalagem: string;
  situacao: string;
  condicao: string;
  unidade_medida: string;
  observacao: string;
  informacao_adicional: string;
  produtosVariacoes?: ProductVariantsResponseApi[];
  estado: string;
  estoque: string;
  estoquemin: string;
  sku: string;
  best_sale: boolean;
  largura: number;
  altura: number;
  comprimento: number;
  peso: string;
  tempogarantia: string;
  fornecedorid: string;
  mais_vendido?: string;
  destaque?: number;
  tipo_venda?: number;
};
type ProductRequestApi = {
  id: number;
  nome: string;
  descricao: string;
  descricao_curta?: string;
  mais_vendido?: string;
  preco: number | string;
  fotos: any;
  ativado: boolean;
  video?: string;
  code_homologation?: string;
  categoriaid: string;
  subcategoriaid?: string;
  marcaid?: string;
  ncm: string;
  preco_custo: string;
  preco_compra: string;
  profundidade: string;
  data_validade: string;
  unidade_caixa: string;
  tipo_item: string;
  tributos?: string;
  codigo_pai?: string;
  codigo_integracao?: string;
  cest: string;
  volume: string;
  peso_bruto: string;
  gtin_ean: string;
  gtin_ean_embalagem: string;
  situacao: string;
  condicao: string;
  unidade_medida: string;
  observacao: string;
  informacao_adicional: string;
  produtosVariacoes?: ProductVariantsResponseApi[];
  estado?: string;
  estoque: string;
  estoquemin: string;
  sku: string;
  mais_vendido: boolean;
  largura: number;
  altura: number;
  comprimento: number;
  peso: string;
  tempogarantia: string;
  fornecedorid: string;
  destaque?: number;
  tipo_venda?: number;
};
