import z from 'zod';
import { REQUIRED_MESSAGE } from '@/constants/errors';

export const createSchema = z
  .object({
    nome: z.string().nonempty(REQUIRED_MESSAGE),
    descricao: z.string().nonempty(REQUIRED_MESSAGE),
    descricao_curta: z.string().optional().nullable(),
    best_seller: z.boolean().optional(),
    preco: z.string().optional(),
    ncm: z.string().optional(),
    preco_custo: z.string().optional(),
    preco_compra: z.string().optional(),
    profundidade: z.string().nonempty(REQUIRED_MESSAGE),
    data_validade: z.string().optional(),
    unidade_caixa: z.string().nonempty(REQUIRED_MESSAGE),
    tipo_item: z.string().nonempty(REQUIRED_MESSAGE),
    cest: z.string().optional(),
    volume: z.string().optional(),
    peso_bruto: z.string().nonempty(REQUIRED_MESSAGE),
    gtin_ean: z.string().optional(),
    gtin_ean_embalagem: z.string().optional(),
    situacao: z.string().nonempty(REQUIRED_MESSAGE),
    condicao: z.string().nonempty(REQUIRED_MESSAGE),
    unidade_medida: z.string().nonempty(REQUIRED_MESSAGE),
    observacao: z.string().optional(),
    informacao_adicional: z.string().optional(),
    categoriaid: z.string().nonempty(REQUIRED_MESSAGE),
    code_homologation: z.string().optional(),
    subcategoriaid: z.string().optional().nullable(),
    fotos: z.any().optional(),
    video: z.any().optional(),
    produtosVariacoes: z.array(z.object({ sku: z.string().nonempty(REQUIRED_MESSAGE),name: z.string().nonempty(REQUIRED_MESSAGE), stock: z.string().nonempty(REQUIRED_MESSAGE) })).optional(),
    estoque: z.string().nonempty(REQUIRED_MESSAGE),
    estoquemin: z.string().nonempty(REQUIRED_MESSAGE),
    sku: z.string().nonempty(REQUIRED_MESSAGE),
    mais_vendido: z.string().optional(),
    largura: z.string().nonempty(REQUIRED_MESSAGE),
    altura: z.string().nonempty(REQUIRED_MESSAGE),
    comprimento: z.string().nonempty(REQUIRED_MESSAGE),
    peso: z.string().nonempty(REQUIRED_MESSAGE),
    tempogarantia: z.string().max(2).optional(),
    fornecedorid: z.string().optional(),
    destaque: z.any().optional(),
    tipo_venda: z.any().optional(),
  })
